### ISSUE TITLE
eslint-plugin-numeric-separators vs unicorn/numeric-separators-style

### ISSUE THREAD

**Issue by EvgenyOrekhov** [chinanwu/eslint-plugin-numeric-separators#1]
What are the benefits of this plugin over [`unicorn/numeric-separators-style`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/numeric-separators-style.md)?

**Comment by chinanwu** [comment]
None, I reckon! :) I had no idea that existed
